import { env } from 'process';
import 'dotenv/config';
import jwt from 'jsonwebtoken';
import {
  generateAccessTokenFn,
  generateConfirmationTokenFn,
  generateRefreshTokenFn,
  TokenInterface,
} from './types/index';

import User from '../../database/model/User';
import ServerError from '../error/ServerError';

const { REFRESH_TOKEN_SECRET, ACCESS_TOKEN_SECRET, CONFIRMATION_TOKEN_SECRET } = env;

/**
 * Helper function to generate refresh tokens.
 *
 * @param user An instance of User.
 * @returns A promise containing the newly created refresh token.
 */
export const generateRefreshToken: generateRefreshTokenFn = async (user) => {
  if (!REFRESH_TOKEN_SECRET) {
    throw new Error('A refresh token secret was not found as an environment variable.');
  }

  const token = jwt.sign({ audience: user.id }, REFRESH_TOKEN_SECRET, {
    expiresIn: '43200m',
  });

  return token;
};

/**
 * Helper function to generate an access token.
 *
 * @param refreshToken A refresh token generated by the generateRefreshToken function.
 * @returns A promise containing a string value of the newly created access token
 *   containing an encoded user id.
 */
export const generateAccessToken: generateAccessTokenFn = async (refreshToken) => {
  try {
    if (!ACCESS_TOKEN_SECRET) {
      throw new Error('An access token secret was not found as an environment variable.');
    }
    if (!REFRESH_TOKEN_SECRET) {
      throw new Error('A refresh token secret was not found as an environment variable.');
    }

    const decoded = jwt.verify(refreshToken, REFRESH_TOKEN_SECRET) as TokenInterface;

    const user = await User.findOneBy({ id: decoded.audience });
    if (!user) throw new ServerError('Invalid JWT.', 401);

    return jwt.sign({ audience: user.id }, ACCESS_TOKEN_SECRET, { expiresIn: '45s' });
  } catch (error) {
    if (error instanceof Error && error.name === 'TokenExpiredError') {
      throw new ServerError('Your refresh token is expired.', 401);
    }
    throw error;
  }
};

/**
 * Helper function to generate a confirmation token.
 *
 * @param user An instance of User.
 * @returns A promise containing a string value of the newly generated confirmation token
 *   containing an encoded user id.
 */
export const generateConfirmationToken: generateConfirmationTokenFn = async (user) => {
  try {
    if (!CONFIRMATION_TOKEN_SECRET) {
      throw new Error(
        'A confirmation token secret was not found as an environment variable.',
      );
    }
    const token = jwt.sign({ audience: user.id }, CONFIRMATION_TOKEN_SECRET, {
      expiresIn: '30m',
    });

    return token;
  } catch (error) {
    if (error instanceof Error) {
      throw new ServerError(error.message, 400);
    }
    throw error;
  }
};
