const beerTypeNames: readonly string[] = [
  'American Amber Ale',
  'American Pale Ale',
  'Blonde Ale',
  'English-Style Bitter',
  'English-Style Pale Ale (ESB)',
  'American Amber Lager',
  'German-Style Dunkel',
  'German-Style Marzen / Oktoberfest',
  'German-Style Schwarzbier',
  'Vienna-Style Lager',
  'American Brown Ale',
  'English-Style Brown Ale',
  'English-Style Mild',
  'American IPA',
  'English-Style IPA',
  'Imperial India Pale Ale',
  'New England IPA',
  'American-Style Wheat Wine Ale',
  'American Wheat',
  'Belgian-Style Witbier',
  'Berliner-Style Weisse',
  'German-Style Dunkelweizen',
  'German-Style Hefeweizen',
  'American Barley Wine',
  'American Imperial Red Ale',
  'British-Style Barley Wine Ale',
  'English-Style Old Ale',
  'Belgian-Style Blonde Ale',
  'Belgian-Style Dubbel',
  'Belgian-Style Golden Strong Ale',
  'Belgian-Style Pale Ale',
  'Belgian-Style Quadrupel',
  'Belgian-Style Saison',
  'Belgian-Style Tripel',
  'American Cream Ale',
  'French-Style Biere de Garde',
  'California Common',
  'German-Style Altbier',
  'German-Style Kolsch',
  'Irish-Style Red Beer',
  'American Imperial Porter',
  'Baltic-Style Porter',
  'English-Style Brown Porter',
  'Robust Porter',
  'Smoke Porter',
  'American Imperial Stout',
  'American Stout',
  'English-Style Oatmeal Stout',
  'English-Style Sweet Stout (Milk Stout)',
  'Irish-Style Dry Stout',
  'German-Style Bock',
  'German-Style Doppelbock',
  'German-Style Maibock',
  'German-Style Weizenbock',
  'Scotch Ale/Wee Heavy',
  'Scottish-Style Ale',
  'Wild/Sour Beers',
  'American Brett',
  'American Sour',
  'Belgian-Style Fruit Lambic',
  'Belgian-Style Lambic/Gueuze',
  'Contemporary Gose',
  'American Lager',
  'Bohemian-Style Pilsener',
  'European-Style Export',
  'German-Style Helles',
  'German-Style Pilsner',
  'Specialty Beers',
  'American Black Ale',
  'Barrel-Aged Beer',
  'Chocolate Beer',
  'Coffee Beer',
  'Honey Beer',
  'Pumpkin Beer',
  'Rye Beer',
  'Session Beer',
  'Smoke Beer',
];

export default beerTypeNames;
